"""baseline schema

Revision ID: c6bcd9d51c4e
Revises: 
Create Date: 2026-09-03 12:03:22.711256

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa


from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c6bcd9d51c4e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=128), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('variant', sa.String(length=128), nullable=True),
    sa.Column('weight', sa.String(length=64), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('barcode', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('yolo_class_id', sa.Integer(), nullable=True),
    sa.Column('image_path', sa.String(length=512), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('recognition_embedding', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('yolo_class_id', name='uq_products_yolo_class_id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_sku'), ['sku'], unique=True)
        batch_op.create_index(batch_op.f('ix_products_yolo_class_id'), ['yolo_class_id'], unique=False)

    op.create_table('scan_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_token', sa.String(length=64), nullable=False),
    sa.Column('detected_count', sa.Integer(), nullable=False),
    sa.Column('embedding_model', sa.String(length=64), nullable=True),
    sa.Column('candidate_json', sa.Text(), nullable=True),
    sa.Column('selected_product_id', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('margin', sa.Float(), nullable=True),
    sa.Column('result_state', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_logs_result_state'), ['result_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_logs_scan_token'), ['scan_token'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_number', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pdf_path', sa.String(length=512), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_invoice_number'), ['invoice_number'], unique=True)

    op.create_table('product_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=512), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('image_type', sa.String(length=32), nullable=False),
    sa.Column('embedding', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_images_product_id'), ['product_id'], unique=False)

    op.create_table('transaction_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('weight', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_items_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('product_embeddings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_image_id', sa.Integer(), nullable=True),
    sa.Column('embedding', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_image_id'], ['product_images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_embeddings_model_name'), ['model_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_embeddings_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_embeddings_product_image_id'), ['product_image_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_embeddings_product_image_id'))
        batch_op.drop_index(batch_op.f('ix_product_embeddings_product_id'))
        batch_op.drop_index(batch_op.f('ix_product_embeddings_model_name'))

    op.drop_table('product_embeddings')
    with op.batch_alter_table('transaction_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_items_transaction_id'))

    op.drop_table('transaction_items')
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_images_product_id'))

    op.drop_table('product_images')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_invoice_number'))

    op.drop_table('transactions')
    with op.batch_alter_table('scan_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_logs_scan_token'))
        batch_op.drop_index(batch_op.f('ix_scan_logs_result_state'))

    op.drop_table('scan_logs')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_yolo_class_id'))
        batch_op.drop_index(batch_op.f('ix_products_sku'))

    op.drop_table('products')
    # ### end Alembic commands ###